// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestModule module
	public static void test_Lookup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Lookup").withParams(params).execute(context);
	}
	public static void test_Lookup_TImeZone(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Lookup_TImeZone").withParams(params).execute(context);
	}
	public static void test_Mapping(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Mapping").withParams(params).execute(context);
	}
	public static void test_Verify(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Verify").withParams(params).execute(context);
	}
	public static void test_Verify_OK(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Verify_OK").withParams(params).execute(context);
	}
	public static void test_Verify_OKprefix(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.Test_Verify_OKprefix").withParams(params).execute(context);
	}
}