// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package numberverifier.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the NumberVerifier module
	public static numberverifier.proxies.Response response_Response(IContext context, numberverifier.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("NumberVerifier.Response_Response").withParams(params).execute(context);
		return result == null ? null : numberverifier.proxies.Response.initialize(context, result);
	}
	public static numberverifier.proxies.Response sUB_PhoneNumberLookup(IContext context, java.lang.String _phoneNumber, java.lang.String _productToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PhoneNumber", _phoneNumber);
		params.put("ProductToken", _productToken);
		IMendixObject result = (IMendixObject)Core.microflowCall("NumberVerifier.SUB_PhoneNumberLookup").withParams(params).execute(context);
		return result == null ? null : numberverifier.proxies.Response.initialize(context, result);
	}
	public static numberverifier.proxies.Response sUB_PhoneNumberValidation(IContext context, java.lang.String _phoneNumber, java.lang.String _productToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PhoneNumber", _phoneNumber);
		params.put("ProductToken", _productToken);
		IMendixObject result = (IMendixObject)Core.microflowCall("NumberVerifier.SUB_PhoneNumberValidation").withParams(params).execute(context);
		return result == null ? null : numberverifier.proxies.Response.initialize(context, result);
	}
	public static boolean sUB_Validate(IContext context, java.lang.String _phoneNumber, numberverifier.proxies.Response _response, java.lang.String _productToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PhoneNumber", _phoneNumber);
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("ProductToken", _productToken);
		return (java.lang.Boolean) Core.microflowCall("NumberVerifier.SUB_Validate").withParams(params).execute(context);
	}
}